[colors.bright]
black = "#8f909d"
blue = "#8388BD"
cyan = "#9EA2CF"
green = "#7C82BA"
magenta = "#8D92C7"
red = "#7278AF"
white = "#cdcfe1"
yellow = "#7D84C2"

[colors.normal]
black = "#0c0f18"
blue = "#8388BD"
cyan = "#9EA2CF"
green = "#7C82BA"
magenta = "#8D92C7"
red = "#7278AF"
white = "#cdcfe1"
yellow = "#7D84C2"

[colors.primary]
background = "#0c0f18"
foreground = "#cdcfe1"
