[colors.bright]
black = "#999595"
blue = "#C98F54"
cyan = "#9B9AA1"
green = "#B96C3B"
magenta = "#757C84"
red = "#676666"
white = "#dbd5d5"
yellow = "#9A7454"

[colors.normal]
black = "#141312"
blue = "#C98F54"
cyan = "#9B9AA1"
green = "#B96C3B"
magenta = "#757C84"
red = "#676666"
white = "#dbd5d5"
yellow = "#9A7454"

[colors.primary]
background = "#141312"
foreground = "#dbd5d5"
